### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by adeverakonda** [anitagraser/movingpandas#64] opened 2020-04-01 19:10 UTC
Hello,

I'm using Windows 10 with Python 3.7 via Anaconda (Using the February 2020 edition from their website). When I try to use the conda install method for movingpandas, I get a series of errors that say that the specifications are incompatible with the existing python installation (See below image). Is there anything I'm missing/not doing right?

![Python error screenshot](https://user-images.githubusercontent.com/62604130/78176645-d0473f00-742a-11ea-8b13-51c5a10e4c9f.jpg)

**Comment by zouhx11** [comment] 2020-04-10 14:36
I think the problem is bokeh. I think movingpandas should adopt bokeh >= 2.0.0

**Comment by anitagraser** [comment] 2020-04-10 21:49
The bokeh pin has recently been removed https://github.com/anitagraser/movingpandas/commit/5e73a53f3e28c8a6af9dd338f827f9e01ef1ea6b. A new release is in the works.

**Comment by anitagraser** [comment] 2020-04-18 17:52
It's unclear what the existing environment in the above issue looks like. However, conda installing movingpandas in a clean Python 3.7 environment works as documented.

**Comment by anitagraser** [comment] 2020-08-15 13:04
This should be fixed im master, please reopen if necessary

**Closed by anitagraser** 2020-08-15 13:04 UTC
