### ISSUE TITLE
Clip vs Intersecting Trajectory

### ISSUE THREAD

**Issue by kostastheocharoulis** [anitagraser/movingpandas#109] opened 2021-04-29 11:32 UTC
Hi experts

I would like a clarification regarding clipping process. 

I had in my mind that clipping trajectories to an area of interest would **work the same** as intersecting , except for the fact that using clip  will  return **only the part of trajectories inside the polygon**  

I have used ship data example where you may see that intersecting with bridge returns 20  ship_ids while clip 10. 

[2-ship-data_Question_Issue.zip](https://github.com/anitagraser/movingpandas/files/6398137/2-ship-data_Question_Issue.zip)

[2-ship-data_Question_Issue.pdf](https://github.com/anitagraser/movingpandas/files/6406764/2-ship-data_Question_Issue.pdf)

Could you provide me more details  regarding the difference ?

Thanks in advance

**Comment by Dobryk15** [comment] 2021-05-05 16:32
Dear Anita @anitagraser ,
have you included the commit 00ad952, which solves issue #104, into the latest version? 
I'm using version 0.5rc1 and according to this [documentation](https://movingpandas.readthedocs.io/en/v0.5rc1/trajectory.html it is the most) this is the most resent version but it doesn't contain your fix from the commit 00ad952, namely these 2 lines:
`if row['spatial_intersection'].is_empty:`
 `        return None`
As a result, the issue with clip appears again.

There is also a master version. Should I use this or the new version will come soon?

Kind regards,
Ira

**Comment by anitagraser** [comment] 2021-05-05 16:59
Please use master for now if you need clip. I'm trying to get a new release out as soon as I can.

Closing this issue as duplicate of #104. Please reopen if the issue persists in master.

**Closed by anitagraser** 2021-05-05 16:59 UTC

**Comment by anitagraser** [comment] 2021-05-08 17:12
@Dobryk15 v0.6 is now available from conda-forge https://anaconda.org/conda-forge/movingpandas
